'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

def isPentagonal(x):
    if (1+(1+24*x)**0.5) % 6 == 0:
        return True
    return False

def isHexagonal(x):
    if (1+(1+8*x)**0.5) % 4 == 0:
        return True
    return False

def TriPentHexa():
    i = 286
    flag = True
    while flag:
        triangle_number = i*(i+1)/2
        if isPentagonal(triangle_number) and isHexagonal(triangle_number):
            flag = False
        i += 1
    return triangle_number

final = TriPentHexa()
print(final)